steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
   cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'D074337trial_trial'
      space: 'dev'
      credentialsId: 'NEO_DEPLOY'