steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
   cloudFoundryDeploy:
    deployTool: 'cf_native'
    cloudFoundry:
      org: 'testOrg'
      space: 'testSpace'
      credentialsId: 'NEO_DELPOY'