steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
  neoDeploy:
    neoHome: '/sdk/tools/'
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'd074337trial'
      host: 'hanatrial.ondemand.com'