steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'D074337trial_trial'
      space: 'dev'